const bingoMasterArray = {
  japan: [
    //Buying/shopping
    "Buy an onigiri",
    "Buy a non-drink item from a vending machine",
    "Buy a drink flavor you have never had before",
    "Use your Suica card to buy something",
    //Food
    "Food that depicts a character",
    "Food that is more cute than it should be",
    "Gyoza",
    "A dipiction of ramen",
    "Conveyor belt sushi",
    "Fermented Vegies",
    "Any food that came from the ocean",
    "A snack that would be disturbing in the U.S.",
    //Public Transportation
    "Ride a train!",
    "Ride a bus",
    "Ride a bike or scooter",
    "Someone sleeping AND standing on the train",
    "A train conductor",
    //Asakusa
    "The Sky Tree",
    "Tokyo Tower",
    "A dense crowd of tourists",
    //Shinjuku
    "Brave the maze that is Shinjuku station",
    "Selfie with the Shinjuku Godzilla head",
    //Nakano
    "Something hanging from the celing of Nakano Broadway",
    "Get ice cream from Broadway's basement",
    "Something weird from the shops above Nakano Broadway",
    //Interact with locals/use Japanese
    "Ask for a bag at a store",
    "Ask how much something costs",
    "Say thank you and get a thank you back",
    //Culture
    "A Japanese Flag",
    "A tourist in traditional garb (kimono)",
    "Not a tourist in traditional grab (kimono)",
    "Paper lantern",
    "Lucky cat",
    "A depiction of Mt. Fuji",
    "The actual Mt. Fuji",
    "Tori gate",
  ],
  us: [
    "An alert squirrel",
    "An interesting car",
    "The American flag",
    "A large hamburger",
    "Basketball in an unexpected place",
    "Barbeque",
    "A GIANT Drink",
    "A GIANT portion of food",
    "A hotdog loaded with toppings",
    "Water with ice cubes",
    "Something wrapped in bacon",
    "A baseball field in use",
    "A football team's logo",
    "An artistic public statue",
    "Driving on or under a highway overpass",
    "A group of cows",
    "State flag",
    "Pigeons or seagulls trying to steal food",
    "Cowboy hat or boots",
    "Cactus",
    "Artistic graffiti",
    "Delicious looking Bagel",
    "A stack of waffles",
    "Mouth watering pie",
    "Ax throwing",
    "Something interesting from Trader Joes",
    "Eating fast food",
    "A large plot of grass",
    "A tall pine tree",
    "An expansive parking lot",
  ],
};

module.exports = bingoMasterArray;
